# Generated by Django 2.2 on 2019-04-25 21:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='body',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='name',
        ),
        migrations.AddField(
            model_name='snippet',
            name='Arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='Departure',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 21, 23, 44, 333978, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='snippet',
            name='Destination',
            field=models.CharField(default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='snippet',
            name='Email',
            field=models.EmailField(default='unavailable', max_length=254),
        ),
        migrations.AddField(
            model_name='snippet',
            name='Name',
            field=models.CharField(default='unavailable', max_length=50),
        ),
        migrations.AddField(
            model_name='snippet',
            name='Source',
            field=models.CharField(default='NONE', max_length=50),
        ),
    ]
