# Generated by Django 2.2 on 2019-04-25 21:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190426_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='Departure',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 21, 25, 59, 838216, tzinfo=utc)),
        ),
    ]
