# Generated by Django 2.2 on 2019-04-25 22:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190426_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='Departure',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 22, 19, 33, 140844, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='Email',
            field=models.EmailField(default='enter', max_length=254),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='Name',
            field=models.CharField(default='enter', max_length=50),
        ),
    ]
