# Generated by Django 2.2 on 2019-04-26 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190426_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='Departure',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 9, 2, 22, 11408, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='Destination',
            field=models.CharField(default='DELHI', max_length=50),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='Email',
            field=models.EmailField(default='john@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='Name',
            field=models.CharField(default='john', max_length=50),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='Source',
            field=models.CharField(default='BANGALORE', max_length=50),
        ),
    ]
